// Mocks generated by Mockito 5.2.0 from annotations
// in ditonton/test/presentation/bloc/watchlist_hptv_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i9;

import 'package:dartz/dartz.dart' as _i7;
import 'package:ditonton/common/failure.dart' as _i11;
import 'package:ditonton/domain/entities/hptv/hptv.dart' as _i12;
import 'package:ditonton/domain/entities/hptv/hptv_detail.dart' as _i13;
import 'package:ditonton/domain/repositories/hptv_repository.dart' as _i8;
import 'package:ditonton/domain/usecases/hptv/get_watchlist_hptv.dart' as _i2;
import 'package:ditonton/domain/usecases/hptv/get_watchlist_status_hptv.dart'
    as _i3;
import 'package:ditonton/domain/usecases/hptv/remove_watchlist_hptv.dart'
    as _i5;
import 'package:ditonton/domain/usecases/hptv/save_watchlist_hptv.dart' as _i4;
import 'package:ditonton/presentation/bloc/hptv/hptv_watchlist_bloc.dart'
    as _i6;
import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetWatchlistHptv_0 extends _i1.Fake implements _i2.GetWatchlistHptv {
}

class _FakeGetWatchListStatusHptv_1 extends _i1.Fake
    implements _i3.GetWatchListStatusHptv {}

class _FakeSaveWatchlistHptv_2 extends _i1.Fake
    implements _i4.SaveWatchlistHptv {}

class _FakeRemoveWatchlistHptv_3 extends _i1.Fake
    implements _i5.RemoveWatchlistHptv {}

class _FakeHptvWatchlistState_4 extends _i1.Fake
    implements _i6.HptvWatchlistState {}

class _FakeEither_5<L, R> extends _i1.Fake implements _i7.Either<L, R> {}

class _FakeHptvRepository_6 extends _i1.Fake implements _i8.HptvRepository {}

/// A class which mocks [HptvWatchlistBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockHptvWatchlistBloc extends _i1.Mock implements _i6.HptvWatchlistBloc {
  MockHptvWatchlistBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetWatchlistHptv get getWatchlistHptv =>
      (super.noSuchMethod(Invocation.getter(#getWatchlistHptv),
          returnValue: _FakeGetWatchlistHptv_0()) as _i2.GetWatchlistHptv);
  @override
  _i3.GetWatchListStatusHptv get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
              returnValue: _FakeGetWatchListStatusHptv_1())
          as _i3.GetWatchListStatusHptv);
  @override
  _i4.SaveWatchlistHptv get saveWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
          returnValue: _FakeSaveWatchlistHptv_2()) as _i4.SaveWatchlistHptv);
  @override
  _i5.RemoveWatchlistHptv get removeWatchlist => (super.noSuchMethod(
      Invocation.getter(#removeWatchlist),
      returnValue: _FakeRemoveWatchlistHptv_3()) as _i5.RemoveWatchlistHptv);
  @override
  _i6.HptvWatchlistState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeHptvWatchlistState_4()) as _i6.HptvWatchlistState);
  @override
  _i9.Stream<_i6.HptvWatchlistState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i6.HptvWatchlistState>.empty())
          as _i9.Stream<_i6.HptvWatchlistState>);
  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);
  @override
  void add(_i6.HptvWatchlistEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i6.HptvWatchlistEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i6.HptvWatchlistState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void on<E extends _i6.HptvWatchlistEvent>(
          _i10.EventHandler<E, _i6.HptvWatchlistState>? handler,
          {_i10.EventTransformer<E>? transformer}) =>
      super.noSuchMethod(
          Invocation.method(#on, [handler], {#transformer: transformer}),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i10.Transition<_i6.HptvWatchlistEvent, _i6.HptvWatchlistState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i9.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i9.Future<void>);
  @override
  void onChange(_i10.Change<_i6.HptvWatchlistState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}

/// A class which mocks [GetWatchlistHptv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistHptv extends _i1.Mock implements _i2.GetWatchlistHptv {
  MockGetWatchlistHptv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.Either<_i11.Failure, List<_i12.Hptv>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i7.Either<_i11.Failure, List<_i12.Hptv>>>.value(
              _FakeEither_5<_i11.Failure, List<_i12.Hptv>>())) as _i9
          .Future<_i7.Either<_i11.Failure, List<_i12.Hptv>>>);
}

/// A class which mocks [GetWatchListStatusHptv].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusHptv extends _i1.Mock
    implements _i3.GetWatchListStatusHptv {
  MockGetWatchListStatusHptv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.HptvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeHptvRepository_6()) as _i8.HptvRepository);
  @override
  _i9.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
}

/// A class which mocks [RemoveWatchlistHptv].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistHptv extends _i1.Mock
    implements _i5.RemoveWatchlistHptv {
  MockRemoveWatchlistHptv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.HptvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeHptvRepository_6()) as _i8.HptvRepository);
  @override
  _i9.Future<_i7.Either<_i11.Failure, String>> execute(_i13.HptvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#execute, [tv]),
              returnValue: Future<_i7.Either<_i11.Failure, String>>.value(
                  _FakeEither_5<_i11.Failure, String>()))
          as _i9.Future<_i7.Either<_i11.Failure, String>>);
}

/// A class which mocks [SaveWatchlistHptv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistHptv extends _i1.Mock implements _i4.SaveWatchlistHptv {
  MockSaveWatchlistHptv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.HptvRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeHptvRepository_6()) as _i8.HptvRepository);
  @override
  _i9.Future<_i7.Either<_i11.Failure, String>> execute(_i13.HptvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#execute, [tv]),
              returnValue: Future<_i7.Either<_i11.Failure, String>>.value(
                  _FakeEither_5<_i11.Failure, String>()))
          as _i9.Future<_i7.Either<_i11.Failure, String>>);
}
